[project]
name = "fiqci.examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
cirq = [
    "iqm-client[cirq]>=34.0.0, <35.0.0",
    "matplotlib>=3.11.1",
    "notebook>=7.6.1",
    "pylatexenc>=2.10",
    "sympy>=1.14.0",
]
qiskit = [
    "iqm-client[qiskit]>=34.0.0, <35.0.0",
    "matplotlib>=3.11.1",
    "notebook>=7.6.1",
    "pylatexenc>=2.10",
    "qiskit-aer>=0.17.2",
    "qiskit-experiments>=0.14.1",
]
